Kunlun_M/urls.py
# from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Kunlun_M import settings


urlpatterns = [
    path('', include('web.index.urls')),
    path('api/', include('web.api.urls')),
    path('dashboard/', include('web.dashboard.urls')),
    path('backend/', include('web.backend.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

web/backend/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/7/26 14:44
# @Author  : LoRexxar
# @File    : urls.py
# @Contact : lorexxar@gmail.com

from django.urls import path

from web.backend import views

from django.views.decorators.csrf import csrf_exempt

app_name = "backend"
urlpatterns = [
    path('', views.index, name='index'),

    # task log
    path("tasklog/<int:task_id>", views.tasklog, name="tasklog"),
    # task debug log
    path("debuglog/<int:task_id>", views.debuglog, name="debuglog"),
    # download debug log
    path("downloadlog/<int:task_id>", views.downloadlog, name="downloadlog"),

    # upload log
    path("uploadlog", csrf_exempt(views.uploadlog), name="uploadlog")
]

web/dashboard/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/2/8 16:29
# @Author  : LoRexxar
# @File    : urls.py
# @Contact : lorexxar@gmail.com

from django.urls import path
from django.contrib.auth.decorators import login_required

from web.dashboard import views
from web.dashboard.controller import tasks, rules, tampers, project, vendor
from web.dashboard.interface import scanresult

app_name = "dashboard"
urlpatterns = [
    path('', views.index, name='index'),

    # task
    path('tasks/list', login_required(tasks.TaskListView.as_view()), name='tasks_list'),
    path('tasks/detail/<int:task_id>', tasks.TaskDetailView.as_view(), name="task_detail"),

    # projects
    path('projects/list', login_required(project.ProjectListView.as_view()), name='projects_list'),
    path('projects/detail/<int:project_id>', project.ProjectDetailView.as_view(), name="project_detail"),

    # rule
    path('rules/list', login_required(rules.RuleListView.as_view()), name='rules_list'),
    path('rules/detail/<int:rule_id>', rules.RuleDetailView.as_view(), name="rule_detail"),

    # tamper
    path('tampers/list', login_required(tampers.TamperListView.as_view()), name='tampers_list'),
    path('tampers/detail/<int:tamper_id>', tampers.TamperDetailView.as_view(), name="tamper_detail"),

    # vendor
    path('vendors/search', login_required(vendor.VendorDetailView.as_view()), name='vendor_details'),
    path('vendors/list', login_required(vendor.VendorListView.as_view()), name='vendors_list'),
    path('vendors/statistics', login_required(vendor.VendorStatisticsView.as_view()), name='vendors_statistics'),
    path('vendorvulns/<int:vendor_vul_id>', login_required(vendor.VendorVulnDetailView.as_view()), name='vendor_vulns_details'),
    path('vendorvulns/list', login_required(vendor.VendorVulnListView.as_view()), name='vendor_vulns_list'),
    path('vendorvulns/statistics', login_required(vendor.VendorVulnStatisticsView.as_view()), name='vendors_vulns_statistics'),

    # docs
    path("docs", views.docs, name="docs"),

    # user
    path("userinfo", views.userinfo, name="userinfo"),

    # interface
    # scan result
    path('vuls/<int:vul_id>/del', scanresult.ScanResultDelInterfaceView.as_view(), name="vul_del"),
]

web/dashboard/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/2/23 16:38
# @Author  : LoRexxar
# @File    : views.py
# @Contact : lorexxar@gmail.com


from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from web.index.models import ScanTask, Project
from web.index.models import get_and_check_scantask_project_id

from utils.utils import del_sensitive_for_config

from Kunlun_M.settings import API_TOKEN


@login_required
def index(req):

    tasks = ScanTask.objects.all().order_by("-id")[:100]
    for task in tasks:
        task.is_finished = int(task.is_finished)
        task.parameter_config = del_sensitive_for_config(task.parameter_config)

        project_id = get_and_check_scantask_project_id(task.id)
        project = Project.objects.filter(id=project_id).first()

        task.project_name = project.project_name

    data = {'tasks': tasks}

    return render(req, 'dashboard/index.html', data)


@login_required
def docs(req):
    return render(req, 'dashboard/docs.html')


@login_required
def userinfo(req):

    data = {
        "apitoken": API_TOKEN
    }

    return render(req, 'dashboard/userinfo.html', data)

templates/dashboard/tasks/task_detail.html
{% extends "dashboard/base.html" %}
{% block title %}Tasks Detail{% endblock %}

{% block body %}
<div>

<div class="box box-primary">
<div class="box-header with-border
">
  <h3 class="box-title">Task Details</h3>
</div>
<div class="box-body">
  <!-- Date -->
  <!-- Date and time range -->
  <div class="form-group">
    <label>Path:</label>

    <div class="input-group">
      <div class="input-group-addon">
        <i class="fa fa-laptop "></i>
      </div>
      <input type="text" class="form-control pull-right" name="filename" value="{{ task.target_path }}" disabled>
    </div>
    <!-- /.input group -->
  </div>

  <div class="form-group">
    <label>Project:</label>

    <div class="input-group">
      <div class="input-group-addon">
        <i class="fa fa-laptop "></i>
      </div>
        <div type="text" class="form-control pull-right"><a href='{% url 'dashboard:project_detail' project.id %}'>{{ project.id }}.{{ project.project_name }}</a></div>
    </div>
    <!-- /.input group -->
  </div>
  <!-- /.form group -->
</div>
<!-- /.box-body -->
</div>

<div class="box box-info">
<div class="box-header with-border">
  <h3 class="box-title">Task</h3>
</div>
<div class="box-body">

  <div class="form-group">
    <label>Task Name:</label>
    <input type="text" class="form-control my-colorpicker1 colorpicker-element" name="task_name" value="{{ task.task_name }}" disabled>
  </div>
  <!-- /.form group -->
<div class="form-group">
    <label>Task Create Time:</label>

    <div class="input-group">
      <div class="input-group-addon">
        <i class="fa fa-calendar"></i>
      </div>
      <input type="text" class="form-control" data-inputmask="'alias': 'dd/mm/yyyy'" value="{{ task.last_scan_time }}" disabled>
    </div>
    <!-- /.input group -->
</div>

<div class="form-group">
    <label>Task Status:</label>

    <div class="input-group">
      {% if task.is_finished == 0 %}
      <span class="label label-danger">Error</span>
      {% elif task.is_finished == 2 %}
      <span class="label label-warning">Running</span>
      {% elif task.is_finished == 1 %}
      <span class="label label-success">Success</span>
      {% else %}
      <span class="label label-success">{{ task.is_finished }}</span>
      {% endif %}
    </div>
    <!-- /.input group -->
</div>

<div class="form-group">
  <label>Parameter Config:</label>
  <textarea class="form-control" rows="3" placeholder="Some details about task" name="parameter_config" disabled>{{ task.parameter_config }}</textarea>
</div>

<!-- /.box-body -->
</div>


<div class="box-footer">
    <button id="result" type="button" class="btn btn-primary">View Details</button>
</div>
</div>

{% if task.is_finished == 1 %}

<div class="box box-warning">
<div class="box-header with-border">
  <h3 class="box-title">Result</h3>
</div>
<!-- /.box-header -->
<div class="box-body">
    <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>CVI ID</th>
                  <th>Language</th>
                  <th>VulFile Path</th>
                  <th>Source</th>
                  <th>Level</th>
                  <th>Type</th>
                  <th>Is Confirm</th>
                  <th>Operate</th>
                </tr>
                {% for taskresult in taskresults %}
                <tr>
                    <td>{{ taskresult.id }}</td>
                    <td>{{ taskresult.cvi_id }}</td>
                    <td>{{ taskresult.language }}</td>

                    {% if taskresult.cvi_id == '9999' %}
                        <td><a href="{% url 'dashboard:vendor_vulns_details' taskresult.vid %}">{{ taskresult.vulfile_path }}</a></td>
                    {% else %}
                        <td>{{ taskresult.vulfile_path }}</td>
                    {% endif %}

                    {% if taskresult.result_type == 'vendor_source_match' %}
                        <td>
                        {% for rs in taskresult.source_code %}
                        <a href="{{ rs }}">{{ rs }}</a><br>
                        {% endfor %}
                        </td>
                    {% else %}
                    <td>{{ taskresult.source_code }}</td>
                    {% endif %}

                    <td>{{ taskresult.level }}</td>
                    <td>{{ taskresult.result_type }}</td>

                      <td>
                      {% if taskresult.is_unconfirm == 0 %}
                      <span class="label label-success">Yes</span>
                      {% elif  taskresult.is_unconfirm  == 1 %}
                      <span class="label label-danger">No</span>
                      {% else %}
                      <span class="label label-success">{{ taskresult.is_unconfirm }}</span>
                      {% endif %}
                      </td>
                    <td><button id="resultdel" type="button" class="btn-shadow dropdown-toggle btn btn-danger" onclick="delVul('{{ taskresult.id }}')">Delete</button></td>
                  </tr>
                {% endfor %}
              </tbody></table>
    </div>

    {% csrf_token %}

</div>

<!-- /.box-body -->
</div>

<div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">New Evil Functions</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
            <tbody><tr>
              <th>ID</th>
              <th>CVI ID</th>
              <th>New Function</th>
              <th>Origin Function</th>
              <th>Is Active</th>
            </tr>
            {% for newevilfunc in newevilfuncs %}
            <tr>
                <td>{{ newevilfunc.id }}</td>
                <td>{{ newevilfunc.svid }}</td>
                <td>{{ newevilfunc.func_name }}</td>
                <td>{{ newevilfunc.origin_func_name }}</td>

                  <td>
                  {% if newevilfunc.is_active %}
                  <span class="label label-success">Yes</span>
                  {% elif not newevilfunc.is_active %}
                  <span class="label label-danger">No</span>
                  {% else %}
                  <span class="label label-success">{{ newevilfunc.is_active }}</span>
                  {% endif %}
                  </td>

              </tr>
            {% endfor %}
          </tbody></table>
    </div>
<!-- /.box-body -->
</div>
{% endif %}

</form>
</div>
{% endblock %}

{% block script %}

<script>
function delVul(vulid){
  $.get("{% url 'dashboard:vul_del' 654321 %}".replace('654321', vulid), function(data){
      if(data.code == 200){
          location.reload();
      }else{
          alert(data.message)
      }
  })
}

$(document).ready(function(){
  $("#dashboard").removeClass("active menu-open");
  $("#dashboard").find("ul li").removeClass("active");
  $("#tasks").addClass("menu-open");
  $("#tasks").find("ul").find("li#task_list").addClass("active");
  $("#tasks").find("ul").css("display","block");

  $("button#result").click(function () {
      location.href = "{% url 'backend:tasklog' task.id %}?token={{ visit_token }}";
    });

});
</script>
{% endblock %}

templates/dashboard/tasks/tasks_list.html
{% extends "dashboard/base.html" %}
{% block title %}Tasks list{% endblock %}

{% block body %}
<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Tasks List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Project</th>
                  <th>Name</th>
                  <th>Time</th>
                  <th>Status</th>
                  <th>Detail</th>
                </tr>
                {% for task in tasks %}
                <tr>
                    <td><a href="{% url 'dashboard:task_detail' task.id %}">{{ task.id }}</a></td>
                    <td><a href="{% url 'dashboard:project_detail' task.project_id %}">{{ task.project_id }} {{ task.project_name }}</a></td>

                      <td>{{ task.target_path }}</td>
                      <td>{{ task.last_scan_time }}</td>
                      <td>
                      {% if task.is_finished == 0 %}
                      <span class="label label-danger">Error</span>
                      {% elif task.is_finished == -1 %}
                      <span class="label label-danger">Error</span>
                      {% elif task.is_finished == 2 %}
                      <span class="label label-warning">Running</span>
                      {% elif task.is_finished == 1 %}
                      <span class="label label-success">Success</span>
                      {% else %}
                      <span class="label label-success">{{ task.is_finished }}</span>
                      {% endif %}
                      </td>
                      <td>
                      <div class="sparkbar" data-color="#00a65a" data-height="20">{{ task.parameter_config }}</div>
                    </td>
                  </tr>
                {% endfor %}
              </tbody></table>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
            <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="{% url 'dashboard:tasks_list' %}">«</a></li>
                {% for i in page_range %}
                  <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="{% url 'dashboard:tasks_list' %}?p={{ i }}">{{ i }}</a></li>
                {% endfor %}
                  <li class="page-item"><a class="page-link" href="{% url 'dashboard:tasks_list' %}?p={{ max_page }}">»</a></li>
                </ul>
            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
{% endblock %}

{% block script %}

<script>
      $(document).ready(function () {
          $("#dashboard").removeClass("active menu-open");
          $("#dashboard").find("ul li").removeClass("active");
          $("#tasks").addClass("menu-open");
          $("#tasks").find("ul").find("li#task_list").addClass("active");
          $("#tasks").find("ul").css("display","block");
      });
</script>


{% endblock %}