Kunlun_M/urls.py
# from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Kunlun_M import settings


urlpatterns = [
    path('', include('web.index.urls')),
    path('api/', include('web.api.urls')),
    path('dashboard/', include('web.dashboard.urls')),
    path('backend/', include('web.backend.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

web/dashboard/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/2/8 16:29
# @Author  : LoRexxar
# @File    : urls.py
# @Contact : lorexxar@gmail.com

from django.urls import path
from django.contrib.auth.decorators import login_required

from web.dashboard import views
from web.dashboard.controller import tasks, rules, tampers, project, vendor
from web.dashboard.interface import scanresult

app_name = "dashboard"
urlpatterns = [
    path('', views.index, name='index'),

    # task
    path('tasks/list', login_required(tasks.TaskListView.as_view()), name='tasks_list'),
    path('tasks/detail/<int:task_id>', tasks.TaskDetailView.as_view(), name="task_detail"),

    # projects
    path('projects/list', login_required(project.ProjectListView.as_view()), name='projects_list'),
    path('projects/detail/<int:project_id>', project.ProjectDetailView.as_view(), name="project_detail"),

    # rule
    path('rules/list', login_required(rules.RuleListView.as_view()), name='rules_list'),
    path('rules/detail/<int:rule_id>', rules.RuleDetailView.as_view(), name="rule_detail"),

    # tamper
    path('tampers/list', login_required(tampers.TamperListView.as_view()), name='tampers_list'),
    path('tampers/detail/<int:tamper_id>', tampers.TamperDetailView.as_view(), name="tamper_detail"),

    # vendor
    path('vendors/search', login_required(vendor.VendorDetailView.as_view()), name='vendor_details'),
    path('vendors/list', login_required(vendor.VendorListView.as_view()), name='vendors_list'),
    path('vendors/statistics', login_required(vendor.VendorStatisticsView.as_view()), name='vendors_statistics'),
    path('vendorvulns/<int:vendor_vul_id>', login_required(vendor.VendorVulnDetailView.as_view()), name='vendor_vulns_details'),
    path('vendorvulns/list', login_required(vendor.VendorVulnListView.as_view()), name='vendor_vulns_list'),
    path('vendorvulns/statistics', login_required(vendor.VendorVulnStatisticsView.as_view()), name='vendors_vulns_statistics'),

    # docs
    path("docs", views.docs, name="docs"),

    # user
    path("userinfo", views.userinfo, name="userinfo"),

    # interface
    # scan result
    path('vuls/<int:vul_id>/del', scanresult.ScanResultDelInterfaceView.as_view(), name="vul_del"),
]

web/dashboard/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/2/23 16:38
# @Author  : LoRexxar
# @File    : views.py
# @Contact : lorexxar@gmail.com


from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from web.index.models import ScanTask, Project
from web.index.models import get_and_check_scantask_project_id

from utils.utils import del_sensitive_for_config

from Kunlun_M.settings import API_TOKEN


@login_required
def index(req):

    tasks = ScanTask.objects.all().order_by("-id")[:100]
    for task in tasks:
        task.is_finished = int(task.is_finished)
        task.parameter_config = del_sensitive_for_config(task.parameter_config)

        project_id = get_and_check_scantask_project_id(task.id)
        project = Project.objects.filter(id=project_id).first()

        task.project_name = project.project_name

    data = {'tasks': tasks}

    return render(req, 'dashboard/index.html', data)


@login_required
def docs(req):
    return render(req, 'dashboard/docs.html')


@login_required
def userinfo(req):

    data = {
        "apitoken": API_TOKEN
    }

    return render(req, 'dashboard/userinfo.html', data)

templates/dashboard/vendors/vendor_detail.html
{% extends "dashboard/base.html" %}
{% block title %}Vendor Detail{% endblock %}

{% block body %}
<div>

<div class="box box-primary">
    <div class="box-header with-border
    ">
      <h3 class="box-title">Search Result for {{ vendor_name }}</h3>
    </div>
    <div class="box-body">
    <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Project</th>
                  <th>Name</th>
                  <th>Version</th>
                  <th>Language</th>
                  <th>Source</th>
                  <th>Ext</th>
                </tr>
                {% for vendor in vendors %}
                <tr>
                    <td>{{ vendor.id }}</td>
                    <td><a href="{% url 'dashboard:project_detail' vendor.project_id %}">{{ vendor.project_id }}</a></td>

                    <td><a href="{% url 'dashboard:vendor_details'%}?vendorname={{ vendor.name }}">{{ vendor.name }}</a></td>
                      <td>{{ vendor.version }}</td>
                      <td>{{ vendor.language }}</td>
                      <td>{{ vendor.source }}</td>
                      <td>{{ vendor.ext }}</td>
                  </tr>
                {% endfor %}
              </tbody></table>
    </div>

    {% csrf_token %}

</div>

<!-- /.box-body -->
</div>

</div>

<div class="box box-warning">
<div class="box-header with-border">
  <h3 class="box-title">Project contains {{ vendor_name }}</h3>
</div>
<!-- /.box-header -->
<div class="box-body">
    <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Origin</th>
                  <th>Vendor Name</th>
                  <th>Vendor Version</th>
                </tr>
                {% for p in projects %}
                <tr>
                    <td><a href="{% url 'dashboard:project_detail' p.id %}">{{ p.id }} {{ p.project_name }}</a></td>

                    <td>{{ p.project_origin }}</td>
                    <td><a href="{% url 'dashboard:vendor_details'%}?vendorname={{ p.vendor_name }}">{{ p.vendor_name }}</a></td>
                    <td>{{ p.version }}</td>

                </tr>
                {% endfor %}
              </tbody></table>
    </div>

    {% csrf_token %}

</div>

<!-- /.box-body -->
</div>

<div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">Vendor {{ vendor_name }} Vuls</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
            <tbody><tr>
              <th>ID</th>
              <th>Vuln ID</th>
              <th>Title</th>
              <th>Severity</th>
              <th>Cve</th>
              <th>Vendor Name</th>
              <th>Vendor Version</th>
            </tr>
            {% for vuln in vvulns %}
            <tr>
                <td>{{ vuln.id }}</td>
                <td><a href="{{ vuln.reference }}">{{ vuln.vuln_id }}</a></td>

                <td><a href="{% url 'dashboard:vendor_vulns_details' vuln.id %}">{{ vuln.title }}</a></td>
                  <td>{{ vuln.severity }}</td>
                  <td>{{ vuln.cves }}</td>
                  <td>{{ vuln.vendor_name }}</td>
                  <td>{{ vuln.affected_versions }}</td>

              </tr>
            {% endfor %}
          </tbody></table>
    </div>
<!-- /.box-body -->
</div>

</form>
</div>
{% endblock %}

{% block script %}

<script>

$(document).ready(function(){
  $("#dashboard").removeClass("active menu-open");
  $("#dashboard").find("ul li").removeClass("active");
  $("#vendors").addClass("menu-open");
  $("#vendors").find("ul").find("li#task_list").addClass("active");
  $("#vendors").find("ul").css("display","block");


});
</script>
{% endblock %}

templates/dashboard/vendors/vendor_vuln_detail.html
{% extends "dashboard/base.html" %}
{% block title %}Vendor Vuls Detail{% endblock %}

{% block body %}
<div>

<div class="box box-primary">
<div class="box-header with-border">
  <h3 class="box-title">Vendor Vuls Details</h3>
</div>
<div class="box-body">
  <!-- Date -->
  <!-- Date and time range -->
  <div class="form-group">
    <label>Vuln ID:</label>

    <div class="input-group">
      <div class="input-group-addon">
        <i class="fa fa-laptop "></i>
      </div>
      <input type="text" class="form-control pull-right" name="filename" value="{{ vvuln.vuln_id }}" disabled>
    </div>
    <!-- /.input group -->
  </div>

  <div class="form-group">
    <label>Title:</label>

    <div class="input-group">
      <div class="input-group-addon">
        <i class="fa fa-laptop "></i>
      </div>
        <div type="text" class="form-control pull-right" disabled>{{ vvuln.title }}</div>
    </div>
    <!-- /.input group -->
  </div>

  <div class="form-group">
    <label>Vendor Name:</label>

    <div class="input-group">
      <div class="input-group-addon">
        <i class="fa fa-laptop "></i>
      </div>
        <div type="text" class="form-control pull-right" disabled>{{ vvuln.vendor_name }}</div>
    </div>
    <!-- /.input group -->
  </div>

  <div class="form-group">
    <label>Affected Versions:</label>

    <textarea class="form-control" rows="3" placeholder="affect Vendor vension" name="affect_version" disabled>{{ vvuln.affected_versions }}</textarea>
    <!-- /.input group -->
  </div>

  <!-- /.form group -->
  <div class="form-group">
    <label>CVE:</label>
    <input type="text" class="form-control my-colorpicker1 colorpicker-element" name="vvuln" value="{{ vvuln.cves }}" disabled>
  </div>
  <!-- /.form group -->
<div class="form-group">
    <label>Reference:</label>

    <div class="input-group">
        <div type="text" class="pull-right" >
            {% for vr in vvuln_references %}
                <a href="{{ vr }}">{{ vr }}</a><br>
            {% endfor %}
        </div>
    </div>
    <!-- /.input group -->
</div>

<div class="form-group">
    <label>Severity:</label>

    <div class="input-group">
      {% if vvuln.severity > 7 %}
      <span class="label label-danger">HigH</span>
      {% elif vvuln.severity > 4 %}
      <span class="label label-warning">Medium</span>
      {% elif vvuln.severity > 0 %}
      <span class="label label-success">Low</span>
      {% else %}
      <span class="label label-success">{{ vvuln.severity }}</span>
      {% endif %}
    </div>
    <!-- /.input group -->
</div>

<div class="form-group">
  <label>Description:</label>
  <textarea class="form-control" rows="3" placeholder="Some details about Vendor vuls" name="Description" disabled>{{ vvuln.description }}</textarea>
</div>

<!-- /.box-body -->
</div>

</div>


</form>
</div>
{% endblock %}

{% block script %}

<script>

$(document).ready(function(){
  $("#dashboard").removeClass("active menu-open");
  $("#dashboard").find("ul li").removeClass("active");
  $("#tasks").addClass("menu-open");
  $("#tasks").find("ul").find("li#task_list").addClass("active");
  $("#tasks").find("ul").css("display","block");

});
</script>
{% endblock %}

templates/dashboard/vendors/vendors_list.html
{% extends "dashboard/base.html" %}
{% block title %}Vendors list{% endblock %}

{% block body %}
<div>

<form id="fileform" role="form" method="get" enctype="multipart/form-data" action="{% url 'dashboard:vendor_details' %}">


<div class="box box-primary">
    <div class="box-header with-border">
  <h3 class="box-title">Search Vendor</h3>
</div>
<div class="box-body">
  <!-- Date -->
  <!-- Date and time range -->
  <div class="form-group">
    <label>Vendor Name:</label>

    <div class="input-group">
      <div class="input-group-addon">
        <i class="fa fa-laptop "></i>
      </div>
      <input type="text" class="form-control pull-right" name="vendorname" value="" >
    </div>
              ps: use * to indicate wildcard, just like jackson*.
    <!-- /.input group -->
  </div>
  </div>
  <!-- /.box -->
    <div class="box-footer">
        <div class="btn-group">
          <button id="submit" type="submit" class="btn btn-primary">Search</button>
        </div>
  </div>
</div>
</form>
</div>

<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Vendors List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Project</th>
                  <th>Name</th>
                  <th>Version</th>
                  <th>Language</th>
                  <th>Source</th>
                  <th>Ext</th>
                </tr>
                {% for vendor in vendors %}
                <tr>
                    <td><a href="{% url 'dashboard:vendor_details'%}?vendorname={{ vendor.name }}">{{ vendor.id }}</a></td>
                    <td><a href="{% url 'dashboard:project_detail' vendor.project_id %}">{{ vendor.project_id }} {{ vendor.project_name }}</a></td>

                    <td><a href="{% url 'dashboard:vendor_details'%}?vendorname={{ vendor.name }}">{{ vendor.name }}</a></td>
                      <td>{{ vendor.version }}</td>
                      <td>{{ vendor.language }}</td>
                      <td>{{ vendor.source }}</td>
                      <td>{{ vendor.ext }}</td>
                  </tr>
                {% endfor %}
              </tbody></table>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
            <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="{% url 'dashboard:vendors_list' %}">«</a></li>
                {% for i in page_range %}
                  <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="{% url 'dashboard:vendors_list' %}?p={{ i }}">{{ i }}</a></li>
                {% endfor %}
                  <li class="page-item"><a class="page-link" href="{% url 'dashboard:vendors_list' %}?p={{ max_page }}">»</a></li>
                </ul>
            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
{% endblock %}

{% block script %}

<script>
      $(document).ready(function () {
          $("#dashboard").removeClass("active menu-open");
          $("#dashboard").find("ul li").removeClass("active");
          $("#vendors").addClass("menu-open");
          $("#vendors").find("ul").find("li#vendors_list").addClass("active");
          $("#vendors").find("ul").css("display","block");
      });
</script>


{% endblock %}

templates/dashboard/vendors/vendors_statistics.html
{% extends "dashboard/base.html" %}
{% block title %}Vendors Statistics list{% endblock %}

{% block body %}
<div>

<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Vendors Statistics List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Language</th>
                  <th>Count</th>
                </tr>
                {% for vendor in vendors %}
                <tr>
                    <td>{{ vendor.id }}</td>
                    <td><a href="{% url 'dashboard:vendor_details'%}?vendorname={{ vendor.name }}">{{ vendor.name }}</a></td>
                    <td>{{ vendor.language }}</td>
                    <td>{{ vendor.total }}</td>
                  </tr>
                {% endfor %}
              </tbody></table>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
            <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="{% url 'dashboard:vendors_statistics' %}">«</a></li>
                {% for i in page_range %}
                  <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="{% url 'dashboard:vendors_statistics' %}?p={{ i }}">{{ i }}</a></li>
                {% endfor %}
                  <li class="page-item"><a class="page-link" href="{% url 'dashboard:vendors_statistics' %}?p={{ max_page }}">»</a></li>
                </ul>
            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
{% endblock %}

{% block script %}

<script>
      $(document).ready(function () {
          $("#dashboard").removeClass("active menu-open");
          $("#dashboard").find("ul li").removeClass("active");
          $("#vendors").addClass("menu-open");
          $("#vendors").find("ul").find("li#vendors_statistics").addClass("active");
          $("#vendors").find("ul").css("display","block");
      });
</script>


{% endblock %}

templates/dashboard/vendors/vendors_vuln_list.html
{% extends "dashboard/base.html" %}
{% block title %}Vendor Vulns list{% endblock %}

{% block body %}
<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Vendor Vulns List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Vuln ID</th>
                  <th>Title</th>
                  <th>Severity</th>
                  <th>Cve</th>
                  <th>Vendor Name</th>
                  <th>Affected Versions</th>
                </tr>
                {% for vendorvuln in vendorvulns %}
                <tr>
                    <td>{{ vendorvuln.id }}</td>
                    <td><a href="{{ vendorvuln.reference }}">{{ vendorvuln.vuln_id }}</a></td>

                      <td><a href="{% url 'dashboard:vendor_vulns_details' vendorvuln.id %}">{{ vendorvuln.title }}</a></td>
                      <td>{{ vendorvuln.severity }}</td>
                      <td>{{ vendorvuln.cves }}</td>
                      <td>{{ vendorvuln.vendor_name }}</td>
                      <td>{{ vendorvuln.affected_versions }}</td>

                  </tr>
                {% endfor %}
              </tbody></table>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="{% url 'dashboard:vendor_vulns_list' %}">«</a></li>
                {% for i in page_range %}
                  <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="{% url 'dashboard:vendor_vulns_list' %}?p={{ i }}">{{ i }}</a></li>
                {% endfor %}
                  <li class="page-item"><a class="page-link" href="{% url 'dashboard:vendor_vulns_list' %}?p={{ max_page }}">»</a></li>
                </ul>
            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
{% endblock %}

{% block script %}

<script>
      $(document).ready(function () {
          $("#dashboard").removeClass("active menu-open");
          $("#dashboard").find("ul li").removeClass("active");
          $("#vendors").addClass("menu-open");
          $("#vendors").find("ul").find("li#vendor_vulns_list").addClass("active");
          $("#vendors").find("ul").css("display","block");
      });
</script>


{% endblock %}

templates/dashboard/vendors/vendors_vuln_statistics.html
{% extends "dashboard/base.html" %}
{% block title %}Vendors Vul Statistics{% endblock %}

{% block body %}
<div>

<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Vendors Vul Statistics</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Vendor Name</th>
                  <th>High Risk</th>
                  <th>Medium Risk</th>
                  <th>Low Risk</th>
                  <th>Vendor Count</th>
                  <th>Vul Count</th>
                </tr>
                {% for vendorvuln in vendorvulns %}
                <tr>
                    <td>{{ vendorvuln.id }}</td>
                    <td><a href="{% url 'dashboard:vendor_details'%}?vendorname={{ vendorvuln.vendor_name }}">{{ vendorvuln.vendor_name }}</a></td>
                    <td>{{ vendorvuln.high }}</td>
                    <td>{{ vendorvuln.medium }}</td>
                    <td>{{ vendorvuln.low }}</td>
                    <td>{{ vendorvuln.vendor_count }}</td>
                    <td>{{ vendorvuln.total }}</td>
                  </tr>
                {% endfor %}
              </tbody></table>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
            <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="{% url 'dashboard:vendors_vulns_statistics' %}">«</a></li>
                {% for i in page_range %}
                  <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="{% url 'dashboard:vendors_vulns_statistics' %}?p={{ i }}">{{ i }}</a></li>
                {% endfor %}
                  <li class="page-item"><a class="page-link" href="{% url 'dashboard:vendors_vulns_statistics' %}?p={{ max_page }}">»</a></li>
                </ul>
            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
{% endblock %}

{% block script %}

<script>
      $(document).ready(function () {
          $("#dashboard").removeClass("active menu-open");
          $("#dashboard").find("ul li").removeClass("active");
          $("#vendors").addClass("menu-open");
          $("#vendors").find("ul").find("li#vendors_vulns_statistics").addClass("active");
          $("#vendors").find("ul").css("display","block");
      });
</script>


{% endblock %}