Kunlun_M/urls.py
# from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Kunlun_M import settings


urlpatterns = [
    path('', include('web.index.urls')),
    path('api/', include('web.api.urls')),
    path('dashboard/', include('web.dashboard.urls')),
    path('backend/', include('web.backend.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

web/dashboard/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/2/8 16:29
# @Author  : LoRexxar
# @File    : urls.py
# @Contact : lorexxar@gmail.com

from django.urls import path
from django.contrib.auth.decorators import login_required

from web.dashboard import views
from web.dashboard.controller import tasks, rules, tampers, project, vendor
from web.dashboard.interface import scanresult

app_name = "dashboard"
urlpatterns = [
    path('', views.index, name='index'),

    # task
    path('tasks/list', login_required(tasks.TaskListView.as_view()), name='tasks_list'),
    path('tasks/detail/<int:task_id>', tasks.TaskDetailView.as_view(), name="task_detail"),

    # projects
    path('projects/list', login_required(project.ProjectListView.as_view()), name='projects_list'),
    path('projects/detail/<int:project_id>', project.ProjectDetailView.as_view(), name="project_detail"),

    # rule
    path('rules/list', login_required(rules.RuleListView.as_view()), name='rules_list'),
    path('rules/detail/<int:rule_id>', rules.RuleDetailView.as_view(), name="rule_detail"),

    # tamper
    path('tampers/list', login_required(tampers.TamperListView.as_view()), name='tampers_list'),
    path('tampers/detail/<int:tamper_id>', tampers.TamperDetailView.as_view(), name="tamper_detail"),

    # vendor
    path('vendors/search', login_required(vendor.VendorDetailView.as_view()), name='vendor_details'),
    path('vendors/list', login_required(vendor.VendorListView.as_view()), name='vendors_list'),
    path('vendors/statistics', login_required(vendor.VendorStatisticsView.as_view()), name='vendors_statistics'),
    path('vendorvulns/<int:vendor_vul_id>', login_required(vendor.VendorVulnDetailView.as_view()), name='vendor_vulns_details'),
    path('vendorvulns/list', login_required(vendor.VendorVulnListView.as_view()), name='vendor_vulns_list'),
    path('vendorvulns/statistics', login_required(vendor.VendorVulnStatisticsView.as_view()), name='vendors_vulns_statistics'),

    # docs
    path("docs", views.docs, name="docs"),

    # user
    path("userinfo", views.userinfo, name="userinfo"),

    # interface
    # scan result
    path('vuls/<int:vul_id>/del', scanresult.ScanResultDelInterfaceView.as_view(), name="vul_del"),
]

web/index/urls.py
#!/usr/bin/env python
# encoding: utf-8
'''
@author: LoRexxar
@contact: lorexxar@gmail.com
@file: urls.py
@time: 2020/12/3 14:45
@desc:

'''

from django.urls import path

from web.index import views


app_name = "index"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.signin, name='login'),
    path('logout', views.logout, name='logout'),
    path('register/', views.signup, name='register')
]

templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    {% load static %}
    <link rel="icon" href="{% static 'favicon.ico' %}" ><link rel="stylesheet" href="{% static 'css/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<body>
<section class="hero is-info is-large">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <h3>{{ title }}</h3>
          </a>
          <span class="navbar-burger burger" data-target="navbarMenuHeroB">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroB" class="navbar-menu">
          <div class="navbar-end">
            <a class="navbar-item is-active" href="/">
              Home
            </a>

{% if user.is_authenticated %}
    <a class="navbar-item" href="{% url 'dashboard:index' %}">
      Dashboard
    </a>
    <a class="navbar-item">
      Loading
    </a>
    <span class="navbar-item">
      <h3>{{ user }} </h3>
      <a class="button is-success is-outlined" style="margin-left: 10px" href="{% url 'index:logout' %}">  logout</a>
    </span>
{% else %}
            <span class="navbar-item">
              <a class="button is-info is-inverted" href="{% url 'index:register' %}">
                <span class="icon">
                  <i class="fa fa-sign-in"></i>
                </span>
                <span>SignUp</span>
              </a>
            </span>
            <span class="navbar-item">
              <a class="button is-info is-inverted" href="{% url 'index:login' %}">
                <span class="icon">
                  <i class="fa fa-sign-in"></i>
                </span>
                <span>SignIn</span>
              </a>
            </span>
{% endif %}

          </div>
        </div>
      </div>
    </nav>
  </div>

  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        {{ title }}
      </p>
      <p class="subtitle">
        Power by LoRexxar
      </p>
      <div class="content">
        {{ description }}
      </div>
    </div>
  </div>
</section>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    {% load static %}
    <link rel="icon" href="{% static 'favicon.ico' %}" ><link rel="stylesheet" href="{% static 'css/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<body>
  <section class="hero is-medium is-primary is-bold">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <h3>{{ title }}</h3>
          </a>
          <span class="navbar-burger burger" data-target="navbarMenuHeroB">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroB" class="navbar-menu">
          <div class="navbar-end">
            <a class="navbar-item is-active" href="/">
              Home
            </a>

{% block index %}
            <span class="navbar-item">
              <a class="button is-info is-inverted" href="{% url 'index:register' %}">
                <span class="icon">
                  <i class="fa fa-sign-in"></i>
                </span>
                <span>SignUp</span>
              </a>
            </span>
            <span class="navbar-item">
              <a class="button is-info is-inverted" href="{% url 'index:login' %}">
                <span class="icon">
                  <i class="fa fa-sign-in"></i>
                </span>
                <span>SignIn</span>
              </a>
            </span>
{% endblock %}

            </div>
        </div>
      </div>
    </nav>
  </div>

    <div class="hero-body">
    	<div class="container">
	      <h1 class="title">
	        {{ title }}
	      </h1>
	      <p class="subtitle">
	        Login pages for <strong>{{ title }}</strong>!
	      </p>

	    <div class="box back">
            <form id="login" method="post" class="form-signin" action="{% url 'index:login' %}">
              {% csrf_token %}
              <div class="field">
                <div class="control">
                  <input class="input is-large" type="text" placeholder="Username" name="username" autofocus="">
                </div>
              </div>

              <div class="field">
                <div class="control">
                  <input class="input is-large" type="password" placeholder="Password" name="password">
                </div>
              </div>

              <div class="columns">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="notification is-danger is-{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
              </div>
              <div class="columns">
              	<div class="column">
              		<a id="login-btn" class="button is-block is-info">Login</a>
              	</div>
              	<div class="column">
              		<a class="button is-block is-info" href="{% url 'index:register' %}">Register</a>
        	  	</div>


              </div>
            </form>
          </div>
	  	</div>
    </div>
  </section>
<script>
document.getElementById("login-btn").addEventListener("click", function(e){
	e.preventDefault();
	e.stopPropagation();
	document.getElementById("login").submit();
	return false;
});


</script>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    {% load static %}
    <link rel="icon" href="{% static 'favicon.ico' %}" ><link rel="stylesheet" href="{% static 'css/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<body>
  <section class="hero is-medium is-primary is-bold">

  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <h3>{{ title }}</h3>
          </a>
          <span class="navbar-burger burger" data-target="navbarMenuHeroB">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroB" class="navbar-menu">
          <div class="navbar-end">
            <a class="navbar-item is-active" href="/">
              Home
            </a>

{% block index %}
            <span class="navbar-item">
              <a class="button is-info is-inverted" href="{% url 'index:register' %}">
                <span class="icon">
                  <i class="fa fa-sign-in"></i>
                </span>
                <span>SignUp</span>
              </a>
            </span>
            <span class="navbar-item">
              <a class="button is-info is-inverted" href="{% url 'index:login' %}">
                <span class="icon">
                  <i class="fa fa-sign-in"></i>
                </span>
                <span>SignIn</span>
              </a>
            </span>
{% endblock %}

            </div>
        </div>
      </div>
    </nav>
  </div>

    <div class="hero-body">
    	<div class="container">
	      <h1 class="title">
	        {{ title }}
	      </h1>
	      <p class="subtitle">
	        Register pages for <strong>{{ title }}</strong>!
	      </p>

<div class="back box is-half is-offset-one-fifth">

<form id="reg" method="post" class="form-signin" action="{% url 'index:register' %}">

{% csrf_token %}

<div class="field">
  <label class="label">Username</label>
  <div class="control">
    <input id="user" class="input" type="text" placeholder="name" name="username" autofocus>
  </div>
</div>

<div class="field">
  <label class="label">Password</label>
  <div class="control">
    <input id="pass" class="input" type="password" placeholder="password" name="password1" value="">
  </div>
</div>

<div class="field">
  <label class="label">Password confirmation</label>
  <div class="control">
    <input id="pass" class="input" type="password" placeholder="password" name="password2" value="">
  </div>
</div>

<div class="field">
  <label class="label">Email</label>
  <div class="control">
    <input id="email" class="input" type="email" placeholder="email" name="email" value="">
  </div>
</div>

<div class="field">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="notification is-danger is-{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<div class="field is-grouped columns">
  <div class="control column">
    <button id="reg-btn" class="button is-link">Submit</button>
  </div>
  <div class="control column">
    <button id="cancel-btn" class="button is-text">Cancel</button>
  </div>
</div>

</form>

</div>

</div>
</div>
</section>

<script>

document.getElementById("reg-btn").addEventListener("click", function(e){
	e.preventDefault();
	e.stopPropagation();
	document.getElementById("reg").submit();
	return false;
});

document.getElementById("cancel-btn").addEventListener("click", function(e){
	e.preventDefault();
	e.stopPropagation();
	location.href = '{% url 'index:index' %}';
	return false;
});


</script>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>