Kunlun_M/urls.py
# from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Kunlun_M import settings


urlpatterns = [
    path('', include('web.index.urls')),
    path('api/', include('web.api.urls')),
    path('dashboard/', include('web.dashboard.urls')),
    path('backend/', include('web.backend.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

web/dashboard/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/2/8 16:29
# @Author  : LoRexxar
# @File    : urls.py
# @Contact : lorexxar@gmail.com

from django.urls import path
from django.contrib.auth.decorators import login_required

from web.dashboard import views
from web.dashboard.controller import tasks, rules, tampers, project, vendor
from web.dashboard.interface import scanresult

app_name = "dashboard"
urlpatterns = [
    path('', views.index, name='index'),

    # task
    path('tasks/list', login_required(tasks.TaskListView.as_view()), name='tasks_list'),
    path('tasks/detail/<int:task_id>', tasks.TaskDetailView.as_view(), name="task_detail"),

    # projects
    path('projects/list', login_required(project.ProjectListView.as_view()), name='projects_list'),
    path('projects/detail/<int:project_id>', project.ProjectDetailView.as_view(), name="project_detail"),

    # rule
    path('rules/list', login_required(rules.RuleListView.as_view()), name='rules_list'),
    path('rules/detail/<int:rule_id>', rules.RuleDetailView.as_view(), name="rule_detail"),

    # tamper
    path('tampers/list', login_required(tampers.TamperListView.as_view()), name='tampers_list'),
    path('tampers/detail/<int:tamper_id>', tampers.TamperDetailView.as_view(), name="tamper_detail"),

    # vendor
    path('vendors/search', login_required(vendor.VendorDetailView.as_view()), name='vendor_details'),
    path('vendors/list', login_required(vendor.VendorListView.as_view()), name='vendors_list'),
    path('vendors/statistics', login_required(vendor.VendorStatisticsView.as_view()), name='vendors_statistics'),
    path('vendorvulns/<int:vendor_vul_id>', login_required(vendor.VendorVulnDetailView.as_view()), name='vendor_vulns_details'),
    path('vendorvulns/list', login_required(vendor.VendorVulnListView.as_view()), name='vendor_vulns_list'),
    path('vendorvulns/statistics', login_required(vendor.VendorVulnStatisticsView.as_view()), name='vendors_vulns_statistics'),

    # docs
    path("docs", views.docs, name="docs"),

    # user
    path("userinfo", views.userinfo, name="userinfo"),

    # interface
    # scan result
    path('vuls/<int:vul_id>/del', scanresult.ScanResultDelInterfaceView.as_view(), name="vul_del"),
]

web/index/urls.py
#!/usr/bin/env python
# encoding: utf-8
'''
@author: LoRexxar
@contact: lorexxar@gmail.com
@file: urls.py
@time: 2020/12/3 14:45
@desc:

'''

from django.urls import path

from web.index import views


app_name = "index"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.signin, name='login'),
    path('logout', views.logout, name='logout'),
    path('register/', views.signup, name='register')
]

web/dashboard/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/2/23 16:38
# @Author  : LoRexxar
# @File    : views.py
# @Contact : lorexxar@gmail.com


from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from web.index.models import ScanTask, Project
from web.index.models import get_and_check_scantask_project_id

from utils.utils import del_sensitive_for_config

from Kunlun_M.settings import API_TOKEN


@login_required
def index(req):

    tasks = ScanTask.objects.all().order_by("-id")[:100]
    for task in tasks:
        task.is_finished = int(task.is_finished)
        task.parameter_config = del_sensitive_for_config(task.parameter_config)

        project_id = get_and_check_scantask_project_id(task.id)
        project = Project.objects.filter(id=project_id).first()

        task.project_name = project.project_name

    data = {'tasks': tasks}

    return render(req, 'dashboard/index.html', data)


@login_required
def docs(req):
    return render(req, 'dashboard/docs.html')


@login_required
def userinfo(req):

    data = {
        "apitoken": API_TOKEN
    }

    return render(req, 'dashboard/userinfo.html', data)

templates/dashboard/base.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>KunLun-MA | {% block title %}index{% endblock %}</title>
    {% load static %}
  <!-- Tell the browser to be responsive to screen width -->
  <link rel="icon" href="{% static 'favicon.ico' %}" >
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
  <!-- my style -->
  <link rel="stylesheet" href="{% static 'css/default.css' %}">

  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
  <link rel="stylesheet" href="{% static 'css/skins/skin-blue.min.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="{% url 'dashboard:index' %}" class="logo">
      <!-- logo for regular state and mobile devices -->

      <span class="logo-lg"><b>KunLun-</b>MA</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="{% static 'img/1.jpg' %}" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">{{ user }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{% static 'img/1.jpg' %}" class="img-circle" alt="User Image">

              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{% url 'dashboard:userinfo' %}" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'index:logout' %}" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static 'img/1.jpg' %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ user }}</p>
          <!-- Status -->
{% if user.is_authenticated %}
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
{% else %}
          <a href="#"><i class="fa fa-circle .text-danger"></i> Offline</a>
{% endif %}
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="active treeview menu-open" id="dashboard">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a href="{% url 'dashboard:index' %}"><i class="fa fa-circle-o"></i> Dashboard</a></li>
          </ul>
        </li>
          <li class="treeview" id="projects">
          <a href="#"><i class="fa ion-ios-analytics-outline"></i> <span>Projects</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li id="projects_list"><a href="{% url 'dashboard:projects_list' %}"><i class="fa fa-circle-o"></i>Projects List</a></li>
          </ul>
        </li>
         <li class="treeview" id="tasks">
          <a href="#"><i class="fa ion-ios-analytics-outline"></i> <span>Tasks</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li id="task_list"><a href="{% url 'dashboard:tasks_list' %}"><i class="fa fa-circle-o"></i>Tasks List</a></li>
          </ul>
        </li>
        <li class="treeview" id="vendors">
          <a href="#"><i class="fa ion-ios-analytics-outline"></i> <span>Vendors</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li id="vendors_list"><a href="{% url 'dashboard:vendors_list' %}"><i class="fa fa-circle-o"></i>Vendors List</a></li>
            <li id="vendors_statistics"><a href="{% url 'dashboard:vendors_statistics' %}"><i class="fa fa-circle-o"></i>Vendors Statistics</a></li>
            <li id="vendor_vulns_list"><a href="{% url 'dashboard:vendor_vulns_list' %}"><i class="fa fa-circle-o"></i>Vendors Vuln List</a></li>
            <li id="vendors_vulns_statistics"><a href="{% url 'dashboard:vendors_vulns_statistics' %}"><i class="fa fa-circle-o"></i>Vendors Vuln Statistics</a></li>

          </ul>
        </li>
        <li class="treeview" id="rules">
          <a href="#"><i class="fa ion-document-text"></i> <span>Rules</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li id="rule_list"><a href="{% url 'dashboard:rules_list' %}"><i class="fa fa-circle-o"></i>Rules List</a></li>
          </ul>
        </li>
        <li class="treeview" id="tampers">
          <a href="#"><i class="fa ion-android-expand"></i> <span>Tamper</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li id="tamper_list"><a href="{% url 'dashboard:tampers_list' %}"><i class="fa fa-circle-o"></i>Tamper List</a></li>
          </ul>
        </li>
        <li id="docs"><a href="{% url 'dashboard:docs' %}"><i class="fa fa-book"></i> <span>Documentation</span></a></li>

        <li id="user"><a href="{% url 'dashboard:userinfo' %}"><i class="fa ion-person"></i> <span>User</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        {% block body_header %}
      <h1>
        Dashboard
        <small>KunLun-MA Control panel</small>
      </h1>
        {% endblock %}
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
    {% block body %}
      <!--------------------------
        | Your Page Content Here |
        -------------------------->
    {% endblock %}
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Power by LoRexxar
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2018 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="pull-right-container">
                    <span class="label label-danger pull-right">70%</span>
                  </span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
  immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.min.js' %}"></script>

{% block script %}

{% endblock %}

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>

templates/dashboard/index.html
{% extends "dashboard/base.html" %}
{% block body %}
<div class="row">
        <div class="col-lg-2 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3>{% if request.session.tasks_count %}{{ request.session.tasks_count }}{% else %}0{% endif %}</h3>

              <p>Tasks</p>
            </div>
            <div class="icon">
              <i class="ion ion-filing"></i>
            </div>
            <a href="{% url 'dashboard:tasks_list' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-2 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3>{% if  request.session.project_count %}{{  request.session.project_count }}{% else %}0{% endif %}</h3>

              <p>Projects</p>
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
            <a href="{% url 'dashboard:tasks_list' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-2 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3>{% if request.session.vul_count %}{{ request.session.vul_count }}{% else %}0{% endif %}</h3>

              <p>Vuls</p>
            </div>
            <div class="icon">
              <i class="ion ion-ios-pricetags-outline"></i>
            </div>
            <a href="{% url 'dashboard:tasks_list' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>


        <div class="col-lg-2 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3>{% if request.session.rules_count %}{{ request.session.rules_count }}{% else %}0{% endif %}</h3>

              <p>Rules</p>
            </div>
            <div class="icon">
              <i class="ion ion-document-text"></i>
            </div>
            <a href="{% url 'dashboard:rules_list' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <div class="col-lg-2 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-orange">
            <div class="inner">
              <h3>{% if request.session.vendor_vuls_count %}{{ request.session.vendor_vuls_count }}{% else %}0{% endif %}</h3>

              <p>Vendor Vuls</p>
            </div>
            <div class="icon">
              <i class="ion ion-eye-disabled"></i>
            </div>
            <a href="{% url 'dashboard:vendor_vulns_list' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <div class="col-lg-2 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-purple">
            <div class="inner">
              <h3>{% if request.session.tampers_count %}{{ request.session.tampers_count }}{% else %}0{% endif %}</h3>

              <p>Tampers</p>
            </div>
            <div class="icon">
              <i class="ion ion-android-desktop"></i>
            </div>
            <a href="{% url 'dashboard:tampers_list' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>

      </div>
      <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Latest Tasks</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="table-responsive">
                <table class="table no-margin">
                  <thead>
                  <tr>
                    <th>Project</th>
                    <th>Task ID</th>
                    <th>Task Path</th>
                    <th>Item</th>
                    <th>Status</th>
                    <th>Details</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for task in tasks %}
                  <tr>
                    <td><a href="{% url 'dashboard:project_detail' task.project_id %}">{{ task.project_id }} {{ task.project_name }}</a></td>
                    <td><a href="{% url 'dashboard:task_detail' task.id %}">{{ task.id }} {{ task.task_name }}</a></td>
                      <td>{{ task.target_path }}</td>
                      <td>{{ task.last_scan_time }}</td>
                      <td>
                      {% if task.is_finished == 0 %}
                      <span class="label label-danger">Error</span>
                      {% elif task.is_finished == -1 %}
                      <span class="label label-danger">Error</span>
                      {% elif task.is_finished == 2 %}
                      <span class="label label-warning">Running</span>
                      {% elif task.is_finished == 1 %}
                      <span class="label label-success">Success</span>
                      {% else %}
                      <span class="label label-success">{{ task.is_finished }}</span>
                      {% endif %}
                      </td>
                      <td>
                      <div class="sparkbar" data-color="#00a65a" data-height="20">{{ task.parameter_config }}</div>
                    </td>
                  </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.table-responsive -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              <a href="{% url 'dashboard:tasks_list' %}" class="btn btn-sm btn-default btn-flat pull-right">View All Tasks</a>
            </div>
            <!-- /.box-footer -->
          </div>


{% endblock %}

templates/dashboard/userinfo.html
{% extends "dashboard/base.html" %}
{% block title %} UserInfo {% endblock %}

{% block body %}

 <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title">User Profile</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <form role="form">
        <!-- text input -->
        <div class="form-group">
          <label>User</label>
          <input type="text" class="form-control" value="{{ request.user.username }}" disabled>
        </div>
        <div class="form-group">
          <label>Email</label>
          <input type="text" class="form-control" value="{{ request.user.email }}" disabled>
        </div>

        <div class="form-group">
          <label>api-token</label>
          <input type="text" class="form-control" value="{{ apitoken }}" disabled>
        </div>

        <!-- textarea -->
        <div class="form-group">
          <label>Profile</label>
          <textarea class="form-control" rows="3" placeholder="Enter ..." disabled></textarea>
        </div>
      </form>
    </div>
    <!-- /.box-body -->
  </div>
{% endblock %}

{% block script %}

<script>
      $(document).ready(function () {
          $("#dashboard").removeClass("active menu-open");
          $("#dashboard").find("ul li").removeClass("active");
          $("#user").addClass("active");
      });
</script>


{% endblock %}